"""Create database and cep model

Revision ID: 15c89689a1a9
Revises: 
Create Date: 2021-08-14 19:42:35.762486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c89689a1a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=100), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('localidade', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ibge', sa.String(length=100), nullable=True),
    sa.Column('gia', sa.String(), nullable=True),
    sa.Column('ddd', sa.String(length=2), nullable=True),
    sa.Column('siafi', sa.String(length=100), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cep')
    # ### end Alembic commands ###
